### ISSUE TITLE
Regression: maven-plugin 0.11.3 does not resolve old artifact 

### ISSUE THREAD

**Issue by uhafner** [revapi/revapi#175]
I upgraded the maven plugin from 0.11.2 to 0.11.3 and now it does not resolve the old artifact anymore. 
- Build with 0.11.2: https://github.com/jenkinsci/analysis-model/commit/fd2db2d254aef49f44271deecb6bd4434b332dcd
Output:
```
[INFO] --- revapi-maven-plugin:0.11.2:check (run-revapi) @ analysis-model ---
554
[INFO] Comparing [edu.hm.hafner:analysis-model:jar:7.0.5] against [edu.hm.hafner:analysis-model:jar:8.0.0-beta10-SNAPSHOT] (including their transitive dependencies).
555
[INFO] API checks completed without failures.
556
[INFO] ------------------------------------------------------------------------
```
- Build with 0.11.3: https://github.com/jenkinsci/analysis-model/commit/c43045e48c6606aa27f3c06224317bd5ff6cfa44
```
[INFO] --- revapi-maven-plugin:0.11.3:check (run-revapi) @ analysis-model ---
970
[WARNING] Failed to resolve old artifacts: Artifact resolution failed for 'edu.hm.hafner:analysis-model:jar:7.0.2'.. The API analysis will proceed comparing the new archives against an empty archive.
971
[INFO] Comparing [] against [edu.hm.hafner:analysis-model:jar:8.0.0-beta10-SNAPSHOT] (including their transitive dependencies).
972
```

The interesting thing is that it works locally:
```
See also https://github.com/jenkinsci/analysis-model/runs/446971271.

[INFO] --- revapi-maven-plugin:0.11.3:check (run-revapi) @ analysis-model ---
Downloading from central: https://repo1.maven.org/maven2/edu/hm/hafner/analysis-model/7.0.5/analysis-model-7.0.5.pom
Downloading from github: https://maven.pkg.github.com/uhafner/edu/hm/hafner/analysis-model/7.0.5/analysis-model-7.0.5.pom
Downloading from repository.jboss.org: https://repository.jboss.org/nexus/content/repositories/public/edu/hm/hafner/analysis-model/7.0.5/analysis-model-7.0.5.pom
Downloading from repo.jenkins-ci.org: https://repo.jenkins-ci.org/public/edu/hm/hafner/analysis-model/7.0.5/analysis-model-7.0.5.pom
Downloaded from repo.jenkins-ci.org: https://repo.jenkins-ci.org/public/edu/hm/hafner/analysis-model/7.0.5/analysis-model-7.0.5.pom (30 kB at 83 kB/s)
[INFO] Comparing [edu.hm.hafner:analysis-model:jar:7.0.5] against [edu.hm.hafner:analysis-model:jar:8.0.0-beta10-SNAPSHOT] (including their transitive dependenc
```

Maybe the problem is that the artifact is not in maven central, it is in our Jenkins artifactory which is not the first in the list.

Is this related to https://github.com/revapi/revapi/issues/171?

**Comment by metlos** [comment]
Yep, definitely the fallout of #171. I thought the resolution is now completely the same as in Maven, but apparently I've missed something. I'd appreciate if you could take a look at the difference between your local env and your CI - especially the difference in settings.xml etc., that could tell us why you're seeing this...

**Comment by uhafner** [comment]
Ah, I think it worked locally because the artifact was in my `.m2` folder. After deleting it, it does not work here as well.

```
[INFO] --- revapi-maven-plugin:0.11.3:check (run-revapi) @ analysis-model ---
Downloading from central: https://repo1.maven.org/maven2/edu/hm/hafner/analysis-model/7.0.5/analysis-model-7.0.5.jar
Downloading from github: https://maven.pkg.github.com/uhafner/edu/hm/hafner/analysis-model/7.0.5/analysis-model-7.0.5.jar
Downloading from repository.jboss.org: https://repository.jboss.org/nexus/content/repositories/public/edu/hm/hafner/analysis-model/7.0.5/analysis-model-7.0.5.jar
Downloading from repo.jenkins-ci.org: https://repo.jenkins-ci.org/public/edu/hm/hafner/analysis-model/7.0.5/analysis-model-7.0.5.jar
Downloaded from repo.jenkins-ci.org: https://repo.jenkins-ci.org/public/edu/hm/hafner/analysis-model/7.0.5/analysis-model-7.0.5.jar (318 kB at 437 kB/s)
[WARNING] Failed to resolve old artifacts: Artifact resolution failed for 'edu.hm.hafner:analysis-model:jar:7.0.5'.. The API analysis will proceed comparing the new archives against an empty archive.
```
What it strange: on the console (last `Downloaded` line) it reports progress for the download. The correct version is my `.m2` folder afterwards. You tool just reports that it does not find a result.

If you want to test on your own: https://github.com/jenkinsci/analysis-model

**Comment by metlos** [comment]
I just released `revapi-maven-plugin:0.11.4` that should fix this. I also released `revapi-java:0.20.2` which you should upgrade to if possible. 0.20.1 contained a very important fix to reproducibility of the results and 0.20.2 contains a small bugfix to handle computed `serialVersionUid` fields (however rare they may be, they appear in JDK (javax.xml.namespace.QName for example)).

**Comment by uhafner** [comment]
Thanks for fixing, the build is back to green now!

**Comment by alberto1980** [comment]
Hi everyone,

I just tested with this versions and the issue persists

**<revapi-maven-plugin.version>0.11.4</revapi-maven-plugin.version>
<revapi-java.version>0.20.2</revapi-java.version>
<revapi-java-spi.version>0.20.0</revapi-java-spi.version>**

Check goal do not recovery RELEASE version

This is my configuration tag:

```
                        <configuration>
                            <skip>${skip-revapi}</skip>
   
                            <oldVersion>RELEASE</oldVersion>
                             
                            <checkDependencies>${revapi.checkDependencies}</checkDependencies>
                            <alwaysCheckForReleaseVersion>${revapi.alwaysCheckForReleaseVersion}</alwaysCheckForReleaseVersion>
                            <failOnUnresolvedArtifacts>${revapi.failOnUnresolvedArtifacts}</failOnUnresolvedArtifacts>
                            <analysisConfigurationFiles>
                                <configurationFile>
                                    <resource>config/AllFilters.json</resource>
                                </configurationFile>
                            </analysisConfigurationFiles>
							<versionFormat>.*\d+(\.\d*)?(\.\d*)?</versionFormat>
                        </configuration>
```

Could you tell me what is wrong?

Thanks

**Comment by metlos** [comment]
Have you tried running the maven build with `-X`? Does that shed some light on this?
