### ISSUE TITLE
Strange problem not reproducing on different machines

### ISSUE THREAD

**Issue by vmassol** [revapi/revapi#87]
Hi Lukas,

We're having a problem on the xwiki project. On some machines we get the following build error (`mvn revapi:check`):

```
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.9.1:check (default-cli) on project xwiki-platform-resource-servlet: The following API problems caused the build to fail:
[ERROR] java.method.returnTypeTypeParametersChanged: method java.util.Enumeration javax.servlet.GenericServlet::getInitParameterNames() @ org.xwiki.resource.servlet.ResourceReferenceHandlerServlet: The return type changed from 'java.util.Enumeration<java.lang.String>' to 'java.util.Enumeration'. [javax.servlet:servlet-api:jar:2.4]
[ERROR] 
[ERROR] If you're using the semver-ignore extension, update your module's version to one compatible with the current changes (e.g. mvn package revapi:update-versions). If you want to explicitly ignore this change and provide a justification for it, add the following JSON snippet to your Revapi configuration under "revapi.ignore" path:
[ERROR] {
[ERROR]   "code": "java.method.returnTypeTypeParametersChanged",
[ERROR]   "old": "method java.util.Enumeration<java.lang.String> javax.servlet.GenericServlet::getInitParameterNames() @ org.xwiki.resource.servlet.ResourceReferenceHandlerServlet",
[ERROR]   "new": "method java.util.Enumeration javax.servlet.GenericServlet::getInitParameterNames() @ org.xwiki.resource.servlet.ResourceReferenceHandlerServlet",
[ERROR]   "oldType": "java.util.Enumeration<java.lang.String>",
[ERROR]   "newType": "java.util.Enumeration",
[ERROR]   "package": "org.xwiki.resource.servlet",
[ERROR]   "classSimpleName": "ResourceReferenceHandlerServlet",
[ERROR]   "methodName": "getInitParameterNames",
[ERROR]   "elementKind": "method",
[ERROR]   "justification": <<<<< ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE >>>>>
[ERROR] }
[ERROR] -> [Help 1]
```

This is what I see when running with -X:

```
Old API:
API[archives=[org.xwiki.platform:xwiki-platform-resource-servlet:jar:9.4], supplementary=[org.slf4j:slf4j-api:jar:1.7.25, org.apache.tika:tika-core:jar:1.14, org.apache.commons:commons-collections4:jar:4.1, org.xwiki.platform:xwiki-platform-resource-default:jar:9.4, org.xwiki.commons:xwiki-commons-text:jar:9.4, commons-codec:commons-codec:jar:1.10, org.apache.struts:struts-core:jar:1.3.10, javax.inject:javax.inject:jar:1, javax.validation:validation-api:jar:1.0.0.GA, org.xwiki.commons:xwiki-commons-component-api:jar:9.4, net.sf.json-lib:json-lib:jar:jdk15:2.4, org.xwiki.platform:xwiki-platform-resource-api:jar:9.4, org.apache.struts:struts-taglib:jar:1.3.10, org.xwiki.commons:xwiki-commons-configuration-api:jar:9.4, werken-xpath:werken-xpath:jar:0.9.4, org.xwiki.commons:xwiki-commons-environment-common:jar:9.4, org.xwiki.commons:xwiki-commons-component-observation:jar:9.4, org.xwiki.platform:xwiki-platform-container-api:jar:9.4, commons-collections:commons-collections:jar:3.2.2, javax.servlet:javax.servlet-api:jar:3.0.1, org.xwiki.commons:xwiki-commons-environment-api:jar:9.4, org.xwiki.platform:xwiki-platform-model:jar:9.4, org.xwiki.commons:xwiki-commons-stability:jar:9.4, ant:ant:jar:1.6, commons-beanutils:commons-beanutils:jar:1.9.3, commons-lang:commons-lang:jar:2.6, org.xwiki.commons:xwiki-commons-environment-servlet:jar:9.4, com.fasterxml.jackson.core:jackson-annotations:jar:2.8.8, org.xwiki.commons:xwiki-commons-management:jar:9.4, jdom:jdom:jar:1.0, org.apache.velocity:velocity:jar:1.7, org.apache.velocity:velocity-tools:jar:2.0, commons-chain:commons-chain:jar:1.2, org.json:json:jar:20160810, com.fasterxml.jackson.core:jackson-databind:jar:2.8.8, net.java.dev.stax-utils:stax-utils:jar:20070216, org.xwiki.commons:xwiki-commons-observation-api:jar:9.4, sslext:sslext:jar:1.2-0, logkit:logkit:jar:2.0, log4j:log4j:jar:1.2.12, net.sf.ezmorph:ezmorph:jar:1.0.6, org.xwiki.platform:xwiki-platform-url-api:jar:9.4, org.xwiki.commons:xwiki-commons-component-default:jar:9.4, org.xwiki.commons:xwiki-commons-xml:jar:9.4, xml-apis:xml-apis:jar:1.4.01, org.jdom:jdom2:jar:2.0.6, net.sourceforge.htmlcleaner:htmlcleaner:jar:2.16, commons-validator:commons-validator:jar:1.6, com.fasterxml.jackson.core:jackson-core:jar:2.8.8, org.jdom:jdom:jar:1.1.3, commons-logging:commons-logging:jar:1.1, commons-io:commons-io:jar:2.5, xerces:xercesImpl:jar:2.11.0, javax.servlet:servlet-api:jar:2.3, org.xwiki.commons:xwiki-commons-properties:jar:9.4, org.apache.httpcomponents:httpcore:jar:4.4.6, org.xwiki.platform:xwiki-platform-container-servlet:jar:9.4, org.apache.struts:struts-tiles:jar:1.3.10, org.apache.commons:commons-lang3:jar:3.5, org.xwiki.commons:xwiki-commons-velocity:jar:9.4, oro:oro:jar:2.0.8, org.apache.httpcomponents:httpclient:jar:4.5.3, commons-digester:commons-digester:jar:2.1, org.xwiki.commons:xwiki-commons-script:jar:9.4, org.xwiki.commons:xwiki-commons-context:jar:9.4, biz.aQute:bndlib:jar:1.43.0]]

New API:
API[archives=[org.xwiki.platform:xwiki-platform-resource-servlet:jar:9.5-20170615.081341-27], supplementary=[org.slf4j:slf4j-api:jar:1.7.25, javax.servlet:servlet-api:jar:2.4, org.json:json:jar:20170516, org.xwiki.commons:xwiki-commons-cache-api:jar:9.5-20170615.094635-46, org.apache.commons:commons-collections4:jar:4.1, org.javassist:javassist:jar:3.21.0-GA, commons-codec:commons-codec:jar:1.10, org.apache.struts:struts-core:jar:1.3.10, org.xwiki.commons:xwiki-commons-xml:jar:9.5-20170614.163142-42, org.xwiki.platform:xwiki-platform-url-api:jar:9.5-20170615.080457-26, javax.inject:javax.inject:jar:1, org.xwiki.commons:xwiki-commons-text:jar:9.5-20170615.094448-44, javax.validation:validation-api:jar:1.0.0.GA, net.sf.json-lib:json-lib:jar:jdk15:2.4, com.google.code.findbugs:jsr305:jar:3.0.1, org.apache.struts:struts-taglib:jar:1.3.10, org.xwiki.platform:xwiki-platform-container-servlet:jar:9.5-20170615.080552-27, werken-xpath:werken-xpath:jar:0.9.4, commons-configuration:commons-configuration:jar:1.10, xpp3:xpp3_min:jar:1.1.4c, commons-collections:commons-collections:jar:3.2.2, javax.servlet:javax.servlet-api:jar:3.0.1, org.xwiki.commons:xwiki-commons-script:jar:9.5-20170615.094557-44, org.xwiki.commons:xwiki-commons-job:jar:9.5-20170615.095009-47, org.xwiki.commons:xwiki-commons-context:jar:9.5-20170615.094509-44, ant:ant:jar:1.6, commons-beanutils:commons-beanutils:jar:1.9.3, commons-lang:commons-lang:jar:2.6, org.xwiki.commons:xwiki-commons-extension-api:jar:9.5-20170615.095030-50, org.xwiki.commons:xwiki-commons-stability:jar:9.5-20170615.094445-45, org.xwiki.commons:xwiki-commons-management:jar:9.5-20170614.163207-42, org.xwiki.commons:xwiki-commons-environment-api:jar:9.5-20170615.094620-44, com.fasterxml.jackson.core:jackson-annotations:jar:2.8.8, org.xwiki.commons:xwiki-commons-component-observation:jar:9.5-20170615.094500-44, jdom:jdom:jar:1.0, org.apache.velocity:velocity:jar:1.7, org.apache.velocity:velocity-tools:jar:2.0, commons-chain:commons-chain:jar:1.2, com.google.guava:guava:jar:20.0, com.fasterxml.jackson.core:jackson-databind:jar:2.8.8, org.xwiki.commons:xwiki-commons-environment-common:jar:9.5-20170615.094921-44, org.xwiki.platform:xwiki-platform-resource-api:jar:9.5-20170615.080448-26, net.java.dev.stax-utils:stax-utils:jar:20070216, sslext:sslext:jar:1.2-0, org.xwiki.platform:xwiki-platform-model:jar:9.5-20170615.080424-26, org.xwiki.commons:xwiki-commons-component-default:jar:9.5-20170615.094505-44, logkit:logkit:jar:2.0, log4j:log4j:jar:1.2.12, org.xwiki.commons:xwiki-commons-logging-api:jar:9.5-20170615.094532-44, net.sf.ezmorph:ezmorph:jar:1.0.6, org.apache.tika:tika-core:jar:1.15, org.xwiki.platform:xwiki-platform-resource-default:jar:9.5-20170615.080452-26, xml-apis:xml-apis:jar:1.4.01, org.jdom:jdom2:jar:2.0.6, net.sourceforge.htmlcleaner:htmlcleaner:jar:2.16, commons-validator:commons-validator:jar:1.6, com.fasterxml.jackson.core:jackson-core:jar:2.8.8, org.jdom:jdom:jar:1.1.3, commons-logging:commons-logging:jar:1.1, org.xwiki.platform:xwiki-platform-container-api:jar:9.5-20170615.080548-26, org.xwiki.commons:xwiki-commons-configuration-api:jar:9.5-20170615.094513-44, commons-io:commons-io:jar:2.5, xerces:xercesImpl:jar:2.11.0, org.xwiki.commons:xwiki-commons-component-api:jar:9.5-20170615.094453-44, javax.activation:activation:jar:1.1.1, org.apache.httpcomponents:httpcore:jar:4.4.6, org.apache.struts:struts-tiles:jar:1.3.10, org.xwiki.commons:xwiki-commons-velocity:jar:9.5-20170614.163218-42, org.xwiki.commons:xwiki-commons-observation-api:jar:9.5-20170615.094457-44, xmlpull:xmlpull:jar:1.1.3.1, org.xwiki.commons:xwiki-commons-environment-servlet:jar:9.5-20170614.162953-42, org.xwiki.commons:xwiki-commons-properties:jar:9.5-20170615.094951-44, org.reflections:reflections:jar:0.9.11, org.apache.commons:commons-lang3:jar:3.6, com.thoughtworks.xstream:xstream:jar:1.4.10, oro:oro:jar:2.0.8, org.apache.httpcomponents:httpclient:jar:4.5.3, commons-digester:commons-digester:jar:2.1, biz.aQute:bndlib:jar:1.43.0]]
```

What I don't understand is why Revapi finds servlet-api:2.4. When I run `mvn dependency:tree` on that module, I only get version 3.0.1:

```
[INFO] --- maven-dependency-plugin:3.0.1:tree (default-cli) @ xwiki-platform-resource-servlet ---
[INFO] org.xwiki.platform:xwiki-platform-resource-servlet:jar:9.5-SNAPSHOT
[INFO] +- org.xwiki.platform:xwiki-platform-resource-default:jar:9.5-SNAPSHOT:compile
[INFO] |  +- org.jdom:jdom2:jar:2.0.6:compile
[INFO] |  +- org.xwiki.commons:xwiki-commons-environment-api:jar:9.5-SNAPSHOT:compile
[INFO] |  |  \- org.xwiki.commons:xwiki-commons-component-api:jar:9.5-SNAPSHOT:compile
[INFO] |  |     +- org.xwiki.commons:xwiki-commons-stability:jar:9.5-SNAPSHOT:compile
[INFO] |  |     +- org.xwiki.commons:xwiki-commons-text:jar:9.5-SNAPSHOT:compile
[INFO] |  |     +- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] |  |     \- javax.inject:javax.inject:jar:1:compile
[INFO] |  +- org.xwiki.platform:xwiki-platform-resource-api:jar:9.5-SNAPSHOT:compile
[INFO] |  \- org.xwiki.platform:xwiki-platform-model:jar:9.5-SNAPSHOT:compile
[INFO] |     +- org.xwiki.commons:xwiki-commons-properties:jar:9.5-SNAPSHOT:compile
[INFO] |     |  \- javax.validation:validation-api:jar:1.0.0.GA:compile
[INFO] |     +- org.xwiki.commons:xwiki-commons-script:jar:9.5-SNAPSHOT:compile
[INFO] |     +- org.apache.commons:commons-lang3:jar:3.6:compile
[INFO] |     \- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] +- org.xwiki.platform:xwiki-platform-container-servlet:jar:9.5-SNAPSHOT:compile
[INFO] |  +- org.xwiki.commons:xwiki-commons-component-default:jar:9.5-SNAPSHOT:compile
[INFO] |  |  \- org.xwiki.commons:xwiki-commons-component-observation:jar:9.5-SNAPSHOT:compile
[INFO] |  +- org.xwiki.platform:xwiki-platform-container-api:jar:9.5-SNAPSHOT:compile
[INFO] |  +- org.xwiki.commons:xwiki-commons-context:jar:9.5-SNAPSHOT:compile
[INFO] |  +- org.xwiki.commons:xwiki-commons-configuration-api:jar:9.5-SNAPSHOT:compile
[INFO] |  |  \- commons-beanutils:commons-beanutils:jar:1.9.3:compile
[INFO] |  +- org.xwiki.commons:xwiki-commons-environment-servlet:jar:9.5-SNAPSHOT:compile
[INFO] |  |  \- org.xwiki.commons:xwiki-commons-environment-common:jar:9.5-SNAPSHOT:compile
[INFO] |  +- org.xwiki.commons:xwiki-commons-extension-api:jar:9.5-SNAPSHOT:compile
[INFO] |  |  +- org.xwiki.commons:xwiki-commons-observation-api:jar:9.5-SNAPSHOT:compile
[INFO] |  |  +- org.xwiki.commons:xwiki-commons-logging-api:jar:9.5-SNAPSHOT:compile
[INFO] |  |  +- org.xwiki.commons:xwiki-commons-job:jar:9.5-SNAPSHOT:compile
[INFO] |  |  |  +- org.xwiki.commons:xwiki-commons-cache-api:jar:9.5-SNAPSHOT:compile
[INFO] |  |  |  +- org.apache.commons:commons-collections4:jar:4.1:compile
[INFO] |  |  |  +- commons-configuration:commons-configuration:jar:1.10:compile
[INFO] |  |  |  |  \- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  |  |  \- com.thoughtworks.xstream:xstream:jar:1.4.10:compile
[INFO] |  |  |     +- xmlpull:xmlpull:jar:1.1.3.1:compile
[INFO] |  |  |     \- xpp3:xpp3_min:jar:1.1.4c:compile
[INFO] |  |  +- commons-io:commons-io:jar:2.5:compile
[INFO] |  |  +- commons-codec:commons-codec:jar:1.10:compile
[INFO] |  |  \- org.reflections:reflections:jar:0.9.11:compile
[INFO] |  |     +- com.google.guava:guava:jar:20.0:compile
[INFO] |  |     \- org.javassist:javassist:jar:3.21.0-GA:compile
[INFO] |  \- org.xwiki.platform:xwiki-platform-url-api:jar:9.5-SNAPSHOT:compile
[INFO] |     \- org.xwiki.commons:xwiki-commons-velocity:jar:9.5-SNAPSHOT:compile
[INFO] |        +- org.xwiki.commons:xwiki-commons-xml:jar:9.5-SNAPSHOT:compile
[INFO] |        |  +- org.jdom:jdom:jar:1.1.3:compile
[INFO] |        |  +- net.sourceforge.htmlcleaner:htmlcleaner:jar:2.16:compile
[INFO] |        |  +- xerces:xercesImpl:jar:2.11.0:compile
[INFO] |        |  |  \- xml-apis:xml-apis:jar:1.4.01:compile
[INFO] |        |  \- net.java.dev.stax-utils:stax-utils:jar:20070216:compile
[INFO] |        +- org.xwiki.commons:xwiki-commons-management:jar:9.5-SNAPSHOT:compile
[INFO] |        +- org.apache.velocity:velocity:jar:1.7:compile
[INFO] |        +- org.apache.velocity:velocity-tools:jar:2.0:compile
[INFO] |        |  +- commons-digester:commons-digester:jar:2.1:compile
[INFO] |        |  +- commons-chain:commons-chain:jar:1.2:compile
[INFO] |        |  +- commons-validator:commons-validator:jar:1.6:compile
[INFO] |        |  +- oro:oro:jar:2.0.8:compile
[INFO] |        |  +- sslext:sslext:jar:1.2-0:compile
[INFO] |        |  +- org.apache.struts:struts-core:jar:1.3.10:compile
[INFO] |        |  +- org.apache.struts:struts-taglib:jar:1.3.10:compile
[INFO] |        |  \- org.apache.struts:struts-tiles:jar:1.3.10:compile
[INFO] |        +- com.fasterxml.jackson.core:jackson-core:jar:2.8.8:compile
[INFO] |        +- com.fasterxml.jackson.core:jackson-databind:jar:2.8.8:compile
[INFO] |        |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.8.8:compile
[INFO] |        +- net.sf.json-lib:json-lib:jar:jdk15:2.4:compile
[INFO] |        |  \- net.sf.ezmorph:ezmorph:jar:1.0.6:compile
[INFO] |        +- org.json:json:jar:20170516:compile
[INFO] |        \- org.apache.httpcomponents:httpclient:jar:4.5.3:compile
[INFO] |           \- org.apache.httpcomponents:httpcore:jar:4.4.6:compile
[INFO] +- org.apache.tika:tika-core:jar:1.15:compile
[INFO] \- javax.servlet:javax.servlet-api:jar:3.0.1:provided
```

What's even more interesting is that only our CI (Jenkins) and my local machine reproduce the problem. Others (Thomas and Edy for example) can't reproduce it locally...

Any idea about how to investigate this? Any way you could help us?

Thanks a lot!
-Vincent

**Comment by metlos** [comment]
This might have actually just been fixed in `revapi-maven-0.9.5`. Would you mind trying it out?

**Comment by vmassol** [comment]
Hi @metlos Thanks. I'll upgrade to it. However I don't recall if we still have the issue. At least it's not a problem since nobody reported it again recently so I think we could close it for now.

**Comment by metlos** [comment]
Ok, so I'll close this issue. Please open a new one if you find any other problem..
